Task2.6.1
Karbainov/DevEduLMSAutoTests pull request #11
Opened 2022-09-15 20:42 UTC by ViStrashko

Доделан, то что тебе говорил

2022-09-15 21:29 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            Assert.Contains(groups, i => i.Text == "������� C#");
Что это такое?))))

2022-09-15 21:29 UTC, baikovIlya commented on AutoTestsSelenium/Support/Urls.cs
> +        public const string ExpectedLessonsUrl = $"https://piter-education.ru:7074/lessons";
Мне кажется, что тут этого быть не должно

2022-09-16 08:31 UTC, Karbainov requested changes

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupCreateManagerAuthorizaedPage.cs
> +    public class GroupCreateManagerAuthorizaedPage : AbstractManagerAuthorizedPage
GroupCreationManagerPage

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupCreateManagerAuthorizaedPage.cs
> +        public string ChooseCourseById(string courseId)
нужно переделать на название а не ID

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupsManagerAuthorizedPage.cs
> +            .XPath($"//*[text()='Преподаватель:']/parent::div[@class='groups-list']//span")).ToList();
убрать энтер

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupsManagerAuthorizedPage.cs
> +        public List<IWebElement> ListTeachersInGroup => _driver.FindElements(By
TeachersInGroup

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/LessonsStudentAuthorizedPage.cs
> +        public List<IWebElement> ListStudentGroups => _driver.FindElements(By.XPath($"//*[@class='tab-container']")).ToList();
+1

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/LessonsTeacherAuthorizedPage.cs
> +        public List<IWebElement> ListTeacherGroups => _driver.FindElements(By.XPath($"//*[@class='tab-container']")).ToList();
+1

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/LessonsTutorAuthorizedPage.cs
> +        public List<IWebElement> ListTutorGroups => _driver.FindElements(By.XPath($"//*[@class='tab-container']")).ToList();
+1

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/CheckWorkWithHomeworkStepDefinitions.cs
> +        private TablesClear _tablesClear;
DBCleaner

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            Assert.Equal(Urls.ExpectedLessonsUrl, _driver.Url);
//TODO

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            Assert.Contains(groups, i => i.Text == "������� C#");
todo

2022-09-16 08:31 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            Assert.Contains(groups, i => i.Text == "������� C#");
todo

2022-09-16 17:34 UTC, Karbainov approved these changes

2022-09-16 18:37 UTC, merged