Task2.16.1
Karbainov/DevEduLMSAutoTests pull request #14
Opened 2022-09-16 08:42 UTC by PuzikovaV

В GroupsManagerAuthorizedPage добавила GetAllGroups (для проверки в CancelGroupCreationStepDefinition)
В CreateGroupManagerAuthorizaedPage из GetDesiredCourseByName убрала ClickComboBoxCourses, так как, если вызывать одновременно, то не находится курс. В шаге разбиваю клик и выбор Sleep-ом.
+ CancelGroupCreationStepDefinition и CancelGroup.feature

2022-09-16 09:05 UTC, Karbainov requested changes

2022-09-16 09:05 UTC, Karbainov commented on AutoTestsSelenium/Features/CancelGroupCreation.feature
> +	Given Open a browser and open a page
login page

2022-09-16 09:05 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            foreach (var group in actualGroups)
чет одной строчкой можно сделать

2022-09-16 09:06 UTC, baikovIlya approved these changes

2022-09-19 02:58 UTC, PuzikovaV commented on AutoTestsSelenium/Features/CancelGroupCreation.feature
> +	Given Open a browser and open a page
добавила

2022-09-19 05:16 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            foreach (var group in actualGroups)
исправила

2022-09-19 07:09 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +        public CancelGroupCreationStepDefinition()
Энтер нужен

2022-09-19 07:10 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            List<RegistationModelWithRole> users = table.CreateSet<RegistationModelWithRole>().ToList();
Зачем создавать лист? Ты же его не используешь никак

2022-09-19 07:13 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            Thread.Sleep(1500);
1500 очень много, там скорее всего достаточно 500

2022-09-19 07:13 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            Thread.Sleep(1500);
То же самое

2022-09-19 07:16 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/StatisticsStepDefinitions.cs
> +            _driver = new ChromeDriver();
Это должно быть в конструкторе

2022-09-19 07:18 UTC, baikovIlya commented on AutoTestsSelenium/Support/Models/Request/AuthModel.cs
> +    public class AuthModel
Мы же его удалили

2022-09-19 07:20 UTC, baikovIlya commented on AutoTestsSelenium/Support/Models/Request/GroupCreationRequest.cs
> +    public class GroupCreationRequest
Есть CreateGroupFromBrowser и вот этот, наверное надо оставить только один

2022-09-19 07:21 UTC, baikovIlya commented on DevEduLMSAutoTests.API/Clients/UsersClient.cs
>          }
Энтер между методами

2022-09-19 07:31 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +        public CancelGroupCreationStepDefinition()
доне

2022-09-19 07:31 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            List<RegistationModelWithRole> users = table.CreateSet<RegistationModelWithRole>().ToList();
косяк. исправила

2022-09-19 07:31 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            Thread.Sleep(1500);
доне

2022-09-19 07:31 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/CancelGroupCreationStepDefinition.cs
> +            Thread.Sleep(1500);
доне

2022-09-19 07:32 UTC, PuzikovaV commented on AutoTestsSelenium/StepDefinitions/StatisticsStepDefinitions.cs
> +            _driver = new ChromeDriver();
доне

2022-09-19 07:33 UTC, PuzikovaV commented on DevEduLMSAutoTests.API/Clients/UsersClient.cs
>          }
доне

2022-09-19 07:38 UTC, PuzikovaV commented on AutoTestsSelenium/Support/Models/Request/AuthModel.cs
> +    public class AuthModel
у меня там куча всякого старья...
убрала

2022-09-19 07:39 UTC, PuzikovaV commented on AutoTestsSelenium/Support/Models/Request/GroupCreationRequest.cs
> +    public class GroupCreationRequest
оставила этот

2022-09-19 09:18 UTC, Karbainov approved these changes

2022-09-19 09:18 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateGroupManagerAuthorizaedPage.cs
> +        public const string PageUrl = $"{Urls.Host}/new-group";
private

2022-09-19 09:18 UTC, baikovIlya approved these changes

2022-09-19 09:29 UTC, merged