Task2.6.2
Karbainov/DevEduLMSAutoTests pull request #19
Opened 2022-09-19 21:17 UTC by ViStrashko

Негативный тест на создание группы по элементам страницы

2022-09-19 23:05 UTC, baikovIlya requested changes

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/Features/Groups.feature
>  A short summary of the feature
Описание фичи Максим просил

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/Features/Groups.feature
> +Then Manager create new group in service with empty group name
Нет в названии ожидаемого поведения
Мне кажется, что это должны быть три разных сценария, даже 4(отдельно с тьютором и препом)

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractManagerAuthorizedPage.cs
> +
Не так сделал вроде
Наверху должно быть public IWebElement ButtonAddGroupSideBar => GetButtonAddGroupSideBar();
А метод называется GetButtonAddGroupSideBar()

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractManagerAuthorizedPage.cs
> +            ButtonAddGroupSideBar().Click();
И тогда клик останется старым

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractStudentAuthorizedPage.cs
>          }
Ну тут то же самое

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractTeacherAuthorizedPage.cs
>          }
И тут

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractTutorAuthorizedPage.cs
>          }
+1

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            AuthorizeUser(_manager);
А зачем это в отдельный метод?

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            string expectedMessage = "�� �� ������� ��������";
Сломался русский язык, эти экспектеды не надо в отедльный файл выносить?

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            _groupCreationManagerPage.OpenThisPage();
Это разве не лучше будет в начале шага поставить?

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            _groupCreationManagerPage.OpenThisPage();
+1

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +        public void ThenManagerCreateNewGroupInServiceWithEmptyCourseName(Table table)
Мы же не вводим имя курса, а выбираем курс, нейминг бы поменять
Мне не совсем ясна логика работы метода, та разный экспектед мессадж идёт?

2022-09-19 23:05 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +        public void ThenManagerCreateNewGroupInServiceWithEmptyTeacherAndTutorCheckboxs(Table table)
Это по идее два разных теста, тем более Макс говорил, что без тьютора должно работать

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/Features/Groups.feature
> +Then Manager create new group in service with empty group name
Переделал на три, не брал тьютора, напишу багу на него

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/PageObjects/AbstractManagerAuthorizedPage.cs
> +
Переделал как надо

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/PageObjects/AbstractManagerAuthorizedPage.cs
> +            ButtonAddGroupSideBar().Click();
Переделал

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/PageObjects/AbstractStudentAuthorizedPage.cs
>          }
Переделал

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            AuthorizeUser(_manager);
Сделал как отдельный шаг, без этого метода

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            string expectedMessage = "�� �� ������� ��������";
Это удаленка блин

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +            _groupCreationManagerPage.OpenThisPage();
Сделал на отдельные сценарии, рефреш не понадобился

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +        public void ThenManagerCreateNewGroupInServiceWithEmptyCourseName(Table table)
Переделал, просто затупил с этими названиями

2022-09-20 14:22 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/GroupsStepDefinitions.cs
> +        public void ThenManagerCreateNewGroupInServiceWithEmptyTeacherAndTutorCheckboxs(Table table)
Переделал

2022-09-20 16:36 UTC, baikovIlya approved these changes

2022-09-22 08:20 UTC, Karbainov approved these changes

2022-09-22 08:20 UTC, Karbainov commented
Решай конфликты и еще раз на ревью)

2022-09-22 08:22 UTC, Karbainov commented
Вообще в одном реквесте прям разные задачи, так нельзя вообще делать. Тип удаление из всех пейдж обджей конструкторов тут вообще не место. Это таска отдельная а не просто захотел сделал

2022-09-22 08:46 UTC, Karbainov approved these changes

2022-09-22 09:12 UTC, AnastasiiaA11 approved these changes

2022-09-22 09:16 UTC, merged