Task2.3
Karbainov/DevEduLMSAutoTests pull request #25
Opened 2022-09-22 14:31 UTC by AnastasiiaA11

Методист создает черновик задания, редактирует его. Преподаватель выкладывает это задание. Студент его видит.

2022-09-22 17:44 UTC, baikovIlya requested changes

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/Features/CheckWorkWithHomework.feature
> +	| ЗаданиеЗадание | string      | http://fjfjf.com |
Этот шаг не "Then", а "When". Чтобы шаг был переиспользуемым, стоит добавить шаг для выхода, а не выходить в каком-то конкретном

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/Features/CheckWorkWithHomework.feature
> +	Then Teacher click button publish
Тоже не "Then". "Then" - это проверки, ожидаемый результат

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/Features/CreatingHomeworkByMethodologist.feature
> +	Then Student should sees homework
Сценарий звучит вполне логично, только надо скорректировать "When"\"Then"

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/AbstractTeacherAuthorizedPage.cs
> +        public IWebElement ButtonAddHomeworksSideBar => _driver.FindElement(By.XPath($"//*[text()='Выдача заданий']/.."));
Уже есть выше на строку

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkCreationMethodistPage.cs
> +        public IWebElement NameHomework => _driver.FindElement(By.XPath("//input[@class='form-input']"));
Надо указать в названии, что за элемент - TextBoxNameHomework

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkCreationMethodistPage.cs
> +        public IWebElement DescriptionHomework => _driver.FindElement(By.XPath("//textarea[@class='form-input']"));
+1

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkCreationMethodistPage.cs
> +            GetChoiceGroupNumberButton(groupName).Click();
Если у тебя это не свойство, а метод, то нет смысла выносить ожидание в отдельный приватный метод, прямо тут лучше написать

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkCreationTeacherPage.cs
> +    public class HomeworkCreationTeacherPage : AbstractPage
Наследуется не от абстрактной пейджы, а как минимум от AbstractTeacherPage

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkCreationTeacherPage.cs
> +
Лишние энтеры

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworkExtraditionTeacherPage.cs
> +        public void ClickNumberGroupRadiobox(string groupName)
RadioButton)))

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworksDraftTeacher.cs
> +
Энтеры надо убрать тут и в конце

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworksStudentPage.cs
> +
Эти элементы находятся на разных страницах, некоторые на этой, а некоторые на HomeworkAnswerStudentsPage
На этой идёт выбор домашки и переход на её страницу, а там уже ответы

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/HomeworksTeacherPage.cs
> -        public void ClickGoToTaskButton(string taskName)
Зачем метод удалила? Он тут нужен

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +        [Given(@"Authorization user as methodist")]
Максим говорил, что лучше использовать всем один шаг какой-то, а то их наплодили уже тыщу штук одинаковых с авторизацией, просто названия у всех разные

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +             HomeworkCreationMethodistPage _homeworkMethodist;
У тебя две страницы в одном шаге, причём от разных пользователей, явно не так что-то

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +            _homeworkMethodist = new HomeworkCreationMethodistPage();
Т.к. это больше не приватное поле класса, а просто переменная, то из названий надо убрать _

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +        public void ThenTeacherAuthorization(Table table)
Опять же, незачем разные шаги на авторизацию

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +            _homeworkExtraditionTeacherPage.ClickHomeworksButton();
У тебя шаг про студента, а пейджа используется учительская - точно не так должно быть

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +        private void AuthorizeUser(SwaggerSignInRequest user)
Есть же шаг на авторизацию, зачем этот метод?

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/StatisticsStepDefinitions.cs
> -            page.ClickExitButton();
Это не так должно быть, точно. Должна быть кнопка выхода, откуда это?

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/StatisticsStepDefinitions.cs
> +            //Assert.Equal(expectedResults, actualResults);
Ты зачем мой шаг закомментировала?

2022-09-22 17:44 UTC, baikovIlya commented on AutoTestsSelenium/Support/Models/Request/AddNewHomework.cs
> +}
Макс сказал, что на этом проекте не существует Response моделей, так что и папки Response тоже. Эта модель есть в папке Models

2022-09-22 17:52 UTC, baikovIlya requested changes

2022-09-22 17:52 UTC, baikovIlya commented on AutoTestsSelenium/Features/CreatingHomeworkByMethodologist.feature
> +	And Teacher authorization
Зачем роль здесь в таблице? Для авторизации используется модель из двух полей всего

2022-09-22 17:52 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologistDefinitions.cs
> +            CheckingUserInGroupModel checkingModel = table.CreateInstance<CheckingUserInGroupModel>();
И модель эта зачем? Есть нормальный шаг на авторизацию с пейджами уже, а тут даже модель из названия видно что не та

2022-09-23 03:05 UTC, PuzikovaV requested changes
В общем, Илья уже все написал ))

2022-09-23 06:56 UTC, Karbainov approved these changes

2022-09-23 06:56 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/AbstractTeacherAuthorizedPage.cs
> +        public IWebElement ButtonAddHomeworksSideBar => _driver.FindElement(By.XPath($"//*[text()='Выдача заданий']/.."));
8 и 9 одинаковые?

2022-09-23 06:56 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/AbstractTeacherAuthorizedPage.cs
> +
+1

2022-09-23 06:56 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/AbstractTeacherAuthorizedPage.cs
> +
+2

2022-09-23 06:56 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/HomeworkCreationMethodistPage.cs
> +        private IWebElement GetChoiceGroupNumberButton(string groupName)
публицизировать

2022-09-23 06:56 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/HomeworkCreationTeacherPage.cs
> +
+1

2022-09-24 19:52 UTC, baikovIlya approved these changes
Мне не нравяться только перепутанные "When"\"Then" и то что у тебя нет нигде проверок. Без проверок это не тесты

2022-09-24 19:52 UTC, baikovIlya commented on AutoTestsSelenium/Support/Models/AddNewHomework.cs
> +        public string CourseName { get; set; }
Ты нигде не пользуешься данным свойством, его бы удалить. Ты везде передаёшь просто через отдельную стрингу, на это свойтво даже ссылок нет. Я посмотрел, если его удалить, то ничего не меняется и не ломается

2022-09-26 08:06 UTC, PuzikovaV approved these changes

2022-09-26 15:18 UTC, baikovIlya approved these changes

2022-09-26 15:30 UTC, merged