2.23.3 Исправила Waitings
Karbainov/DevEduLMSAutoTests pull request #26
Opened 2022-09-22 20:56 UTC by milanamaksina

Исправила то о чем говорили на прошлом уроке

2022-09-22 21:26 UTC, baikovIlya requested changes

2022-09-22 21:26 UTC, baikovIlya commented on AutoTestsSelenium/Features/Registration.feature
>  	And Authorize user in service
Используй имеющийся в проекте шаг для авторизации, который с табличкой, например When(And) Authorize user. Максим сказал, что лучше пусть будет больше таблиц, но все шаги будут не уникальными, а переиспользуемыми, чтобы каждый не писал свои шаги на одно и то же действие

2022-09-22 21:26 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/RegistrationStepDefinitions.cs
Максим вроде ещё говорил, что надо добавить проверку того, что окно пропадает

2022-09-23 07:04 UTC, Karbainov requested changes

2022-09-23 07:04 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/RegistrationPage.cs
добавить получение модального окошечка

2022-09-23 07:04 UTC, Karbainov commented on AutoTestsSelenium/Features/Registration.feature
>  	Then User should see the welcome modal window
+ шаг на дисапиер

2022-09-23 07:04 UTC, Karbainov commented on AutoTestsSelenium/Features/Registration.feature
>  	And Authorize user in service
угу

2022-09-27 19:57 UTC, baikovIlya approved these changes

2022-09-28 07:36 UTC, Karbainov approved these changes

2022-09-28 07:37 UTC, merged