Change to Examples
Karbainov/DevEduLMSAutoTests pull request #38
Opened 2022-09-27 00:34 UTC by ViStrashko

2022-09-27 09:32 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/GroupEditingManagerPage.cs
> +        public void ChooseTutor(List<string> fullNamesOfTutors)
Если метод выбирает несколько тьюторов, то его стоит назвать ChooseTutors

2022-09-27 09:32 UTC, baikovIlya commented on AutoTestsSelenium/PageObjects/GroupEditingManagerPage.cs
> +        public void ChooseTeacher(List<string> fullNamesOfTeachers)
Если метод выбирает несколько тьюторов, то его стоит назвать ChooseTeachers

2022-09-27 13:50 UTC, ViStrashko commented on AutoTestsSelenium/PageObjects/GroupEditingManagerPage.cs
> +        public void ChooseTeacher(List<string> fullNamesOfTeachers)
Оке, а чего не апрув

2022-09-27 15:34 UTC, baikovIlya approved these changes

2022-09-28 08:00 UTC, Karbainov requested changes
В остальном все хорошо, как вернешь можешь лить

2022-09-28 08:00 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupCreationManagerPage.cs
> +        public IWebElement GetLabelElementByText(string errorMessege)
не, нужно проверять что сообщения еще и в правильных местах появились) Верните пожалуйста 3 разных эррора) они тут в свойствах живут)

2022-09-28 08:00 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/GroupEditingManagerPage.cs
> +            return _driver.FindElement(By.XPath($"//*[text()='{errorMessege}']"));
+1

2022-09-29 23:01 UTC, merged