Feature "User Change Profile Photo"
Karbainov/DevEduLMSAutoTests pull request #40
Opened 2022-09-27 22:38 UTC by baikovIlya

2022-09-28 08:19 UTC, Karbainov requested changes

2022-09-28 08:19 UTC, Karbainov commented on AutoTestsSelenium/Features/UserChangeProfilePhoto.feature
> +	And Add new photo
это 4 шага, выбрать фото, кликнуть сохранить, дождаться пропажи, сделать рефреш

+ можно добавить 2 нетса (отмена и изменение авы) если будет скучно

2022-09-28 20:39 UTC, ViStrashko approved these changes

2022-09-28 20:39 UTC, ViStrashko commented on AutoTestsSelenium/Features/UserChangeProfilePhoto.feature
> +	And Open profile page
When отсюда Макс сказал, в группах у меня было так, как сейчас у тебя

2022-09-28 20:39 UTC, ViStrashko commented on AutoTestsSelenium/Features/UserChangeProfilePhoto.feature
> +	When Open DevEdu web site https://piter-education.ru:7074/
+1

2022-09-28 20:39 UTC, ViStrashko commented on AutoTestsSelenium/Features/UserChangeProfilePhoto.feature
> +	When Open profile page
Тут вот как надо

2022-09-28 20:39 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/UserChangeProfilePhotoStepDefinitions.cs
> +        [When(@"Open profile page")]
Тут тогда назови шаг Click name user, раз уж клик юзаешь

2022-09-28 20:39 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/UserChangeProfilePhotoStepDefinitions.cs
> +            string scrypt = "document.querySelector('#root > div.modal-background > div > div.buttons-container > label > input').setAttribute('class','display')";
Надо определится, явно или неявно определяем тип данных, у тебя везде вперемешку, я посмотрел, что ты var используешь и переделал свой код под тебя везде, включая название page, вместо тех длинных, что были у меня

2022-09-28 21:06 UTC, baikovIlya commented on AutoTestsSelenium/StepDefinitions/UserChangeProfilePhotoStepDefinitions.cs
> +            string scrypt = "document.querySelector('#root > div.modal-background > div > div.buttons-container > label > input').setAttribute('class','display')";
Поменял на var-ы, имена на page

2022-09-29 16:28 UTC, Karbainov approved these changes

2022-09-29 16:38 UTC, merged