Task2.5.1
Karbainov/DevEduLMSAutoTests pull request #9
Opened 2022-09-15 15:13 UTC by AnastasiiaA11

2022-09-15 16:11 UTC, Karbainov requested changes

2022-09-15 16:11 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +        public override void OpenThisPage()=> _driver.Navigate().GoToUrl(PageUrl);
вообще согласен) Красиво) Но нужно прийти к одной конвенции по проекты, как вы методы в пэйдж обджах делать будете.

2022-09-15 16:11 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/CheckWorkWithHomeworkStepDefinitions.cs
> +
В пустом шаге нужно оставлять ошибку и TODO, если хочешь это лить в мэйн)

2022-09-15 16:11 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologist.cs
>              Thread.Sleep(1000);
слип нужен? Если для красоты - убираем)

2022-09-15 17:33 UTC, AnastasiiaA11 commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologist.cs
>              Thread.Sleep(1000);
слип нужен, без него не двигается

2022-09-15 17:48 UTC, ViStrashko commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologist.cs
> +            _driver.FindElement(_singInWindow.XPathSingInButton).Click();
Настя, все эти штуки тоже надо через обджект сделать, везже, где зеленае

2022-09-15 17:49 UTC, AnastasiiaA11 commented on AutoTestsSelenium/StepDefinitions/CheckWorkWithHomeworkStepDefinitions.cs
> +
throw new PendingStepException(); а todo?

2022-09-15 17:49 UTC, AnastasiiaA11 commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +        public override void OpenThisPage()=> _driver.Navigate().GoToUrl(PageUrl);
переделаю тогда

2022-09-16 08:02 UTC, Karbainov requested changes

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +
лишний ентер

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +        {
добавить дабл клик

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +            textBoxStartDate.SendKeys(endDate);
+1

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +
свойства называют с большой буквы

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +        public string _groupName;
поля не бывают публичными

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/PageObjects/CreateHomeworkTeacherAuthorizedPage.cs
> +        public IWebElement radioButtonNumberGroup => _driver.FindElement(By.XPath($"//*[text()='{_groupName}']/ancestor::*[@class='radio-button']"));
вынести в метод

2022-09-16 08:02 UTC, Karbainov commented on AutoTestsSelenium/StepDefinitions/CheckWorkWithHomeworkStepDefinitions.cs
> +            throw new PendingStepException();
//TODO: 2.8.2 Описание

2022-09-16 09:51 UTC, AnastasiiaA11 commented on AutoTestsSelenium/StepDefinitions/CheckWorkWithHomeworkStepDefinitions.cs
> +            throw new PendingStepException();
смотри,этот кусок относится к 2.5, я его поменяю в той ветке, пусть лучше так будет

2022-09-16 09:53 UTC, AnastasiiaA11 commented on AutoTestsSelenium/StepDefinitions/CreatingHomeworkByMethodologist.cs
> +            _driver.FindElement(_singInWindow.XPathSingInButton).Click();
это будет в ветке 2.5

2022-09-16 17:30 UTC, Karbainov approved these changes

2022-09-17 12:37 UTC, merged